apiVersion: apps/v1
kind: Deployment
metadata:
  name: salut-modbus
  labels:
    app: salut-modbus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salut-modbus
  template:
    metadata:
      labels:
        app: salut-modbus
    spec:
      containers: 
      - name: salut-modbus
        image: flecsbikubernetes.azurecr.io/com.salz.salut:modbus
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
        ports:
          - containerPort: 502
          - containerPort: 1534
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
