apiVersion: v1
kind: Service
metadata:
  name: salut-test-service
spec:
  selector:
    app: salut-test
  ports:
    - protocol: TCP
      name: modbus
      port: 502
      targetPort: 502
    - protocol: TCP
      name: salut
      port: 1534
      targetPort: 1534
  type: LoadBalancer
